version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: customers
      - name: marketing_campaigns
      - name: order_items
      - name: orders
      - name: payments
      - name: products
      - name: shipments
      - name: suppliers
      - name: support_tickets


  - name : geo
    schema: geo
    tables:
      - name: cities
      - name: countries

  - name: hr
    schema: hr
    tables:
      - name: departments
      - name: employees

    
  - name: inventory
    schema: inventory
    tables:
      - name: warehouses
      - name: stock_movements