etl:
  outputs:
    dev:
      database: ETL_dev
      host: localhost
      password: test123
      port: 5432
      schema: default
      threads: 1
      type: postgres
      user: postgres

    prod:
      database: ETL_prod
      host: localhost
      password: test123
      port: 5432
      schema: default
      threads: 1
      type: postgres
      user: postgres
  target: dev
